name: Docker Image buidl and push CI

on:
  push:
    branches: [ release/* ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Find and Replace Build Identifier
      uses: jacobtomlinson/gha-find-replace@2.0.0
        with:
          find: '"buildIdentifier": ""'
          replace: '"buildIdentifier": "${GITHUB_REF##*/}/${GITHUB_SHA}"'
          include: "src/assets/config/config.json"
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
        
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: cinchy.forms
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}
